### ISSUE TITLE
Correct Dashboard Views

### ISSUE THREAD

**Issue by CateCarroll** [AltruisTech/ECD-Online#4]
Current dashboards don't display/wrap text correctly.

**Comment by simonozzy** [comment]
Aware of this, since use of tabbed view on home page. On to do list.

**Comment by simonozzy** [comment]
Fixed by delaying the chart rendering until the "Dashboard" tab is actually opened.  (Back on it!)
Approach taken:
https://stackoverflow.com/questions/43401936/issue-with-displaying-google-chart-in-a-bootstrap-tab
Deployed to app.* 
Github needs updating with this change.
