### ISSUE TITLE
Staff Link Not Working

### ISSUE THREAD

**Issue by CateCarroll** [AltruisTech/ECD-Online#7]
Link from front data list or individual organisation to the staff page doesnt filter the staff as expected - just shows the whole list.

**Comment by simonozzy** [comment]
Fixed when linking from search table eg. :
http://app.nag.org.za/staffOrg/1066
Will deploy to live app in next few days.
Github needs updating with this change.

I now may need a way to make this page work again :
http://app.nag.org.za/staff/*
- to scroll through / search a table of all staff - if still required?

Also:
Staff selection (via ID number) is only working up to OrgID 1118 - know issue with Excel formatting of source data - easily fixed on next data refresh.
